VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOD"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Method : cmdCreateLog_click
' Author : gouldd
' Date   : 8/30/2016
' Purpose: List all actions performed as IOD
'---------------------------------------------------------------------------------------
Option Explicit

Private Sub cmdCreateLog_click()
10    frmCreateIODLog.Show
End Sub

